[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
# user = "greeter"

[greeter]
command = "tuigreet -t -s /usr/share/xsessions:/usr/share/wayland-sessions"

# Initial session
[initial_session]
user = "greeter"

# The default session, also known as the greeter.
[default_session]
user = "greeter"
